ARG NODE_VER
FROM node:20.10.0

USER node
WORKDIR /home/node/app

COPY --chown=node:node ./backend/package.json ./backend/package-lock.json ./
RUN npm install

COPY --chown=node:node ./backend/.env ./.env
COPY --chown=node:node ./backend/dist ./dist/

EXPOSE 3000

ENTRYPOINT ["node", "dist/main.js"]